/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanNewRouteImport } from './routes/scan.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminApiHealthRouteImport } from './routes/admin.api-health'
import { Route as ScanScanIdReviewRouteImport } from './routes/scan.$scanId.review'
import { Route as ScanScanIdResultRouteImport } from './routes/scan.$scanId.result'
import { Route as ScanScanIdChecklistRouteImport } from './routes/scan.$scanId.checklist'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanNewRoute = ScanNewRouteImport.update({
  id: '/scan/new',
  path: '/scan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiHealthRoute = AdminApiHealthRouteImport.update({
  id: '/admin/api-health',
  path: '/admin/api-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanScanIdReviewRoute = ScanScanIdReviewRouteImport.update({
  id: '/scan/$scanId/review',
  path: '/scan/$scanId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanScanIdResultRoute = ScanScanIdResultRouteImport.update({
  id: '/scan/$scanId/result',
  path: '/scan/$scanId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanScanIdChecklistRoute = ScanScanIdChecklistRouteImport.update({
  id: '/scan/$scanId/checklist',
  path: '/scan/$scanId/checklist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/readiness': typeof ReadinessRoute
  '/settings': typeof SettingsRoute
  '/admin/api-health': typeof AdminApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/scan/new': typeof ScanNewRoute
  '/scan/$scanId/checklist': typeof ScanScanIdChecklistRoute
  '/scan/$scanId/result': typeof ScanScanIdResultRoute
  '/scan/$scanId/review': typeof ScanScanIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/readiness': typeof ReadinessRoute
  '/settings': typeof SettingsRoute
  '/admin/api-health': typeof AdminApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/scan/new': typeof ScanNewRoute
  '/scan/$scanId/checklist': typeof ScanScanIdChecklistRoute
  '/scan/$scanId/result': typeof ScanScanIdResultRoute
  '/scan/$scanId/review': typeof ScanScanIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/readiness': typeof ReadinessRoute
  '/settings': typeof SettingsRoute
  '/admin/api-health': typeof AdminApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/scan/new': typeof ScanNewRoute
  '/scan/$scanId/checklist': typeof ScanScanIdChecklistRoute
  '/scan/$scanId/result': typeof ScanScanIdResultRoute
  '/scan/$scanId/review': typeof ScanScanIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cargo'
    | '/compare'
    | '/history'
    | '/login'
    | '/readiness'
    | '/settings'
    | '/admin/api-health'
    | '/auth/callback'
    | '/scan/new'
    | '/scan/$scanId/checklist'
    | '/scan/$scanId/result'
    | '/scan/$scanId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cargo'
    | '/compare'
    | '/history'
    | '/login'
    | '/readiness'
    | '/settings'
    | '/admin/api-health'
    | '/auth/callback'
    | '/scan/new'
    | '/scan/$scanId/checklist'
    | '/scan/$scanId/result'
    | '/scan/$scanId/review'
  id:
    | '__root__'
    | '/'
    | '/cargo'
    | '/compare'
    | '/history'
    | '/login'
    | '/readiness'
    | '/settings'
    | '/admin/api-health'
    | '/auth/callback'
    | '/scan/new'
    | '/scan/$scanId/checklist'
    | '/scan/$scanId/result'
    | '/scan/$scanId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargoRoute: typeof CargoRoute
  CompareRoute: typeof CompareRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ReadinessRoute: typeof ReadinessRoute
  SettingsRoute: typeof SettingsRoute
  AdminApiHealthRoute: typeof AdminApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ScanNewRoute: typeof ScanNewRoute
  ScanScanIdChecklistRoute: typeof ScanScanIdChecklistRoute
  ScanScanIdResultRoute: typeof ScanScanIdResultRoute
  ScanScanIdReviewRoute: typeof ScanScanIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/new': {
      id: '/scan/new'
      path: '/scan/new'
      fullPath: '/scan/new'
      preLoaderRoute: typeof ScanNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-health': {
      id: '/admin/api-health'
      path: '/admin/api-health'
      fullPath: '/admin/api-health'
      preLoaderRoute: typeof AdminApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$scanId/review': {
      id: '/scan/$scanId/review'
      path: '/scan/$scanId/review'
      fullPath: '/scan/$scanId/review'
      preLoaderRoute: typeof ScanScanIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$scanId/result': {
      id: '/scan/$scanId/result'
      path: '/scan/$scanId/result'
      fullPath: '/scan/$scanId/result'
      preLoaderRoute: typeof ScanScanIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$scanId/checklist': {
      id: '/scan/$scanId/checklist'
      path: '/scan/$scanId/checklist'
      fullPath: '/scan/$scanId/checklist'
      preLoaderRoute: typeof ScanScanIdChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargoRoute: CargoRoute,
  CompareRoute: CompareRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ReadinessRoute: ReadinessRoute,
  SettingsRoute: SettingsRoute,
  AdminApiHealthRoute: AdminApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ScanNewRoute: ScanNewRoute,
  ScanScanIdChecklistRoute: ScanScanIdChecklistRoute,
  ScanScanIdResultRoute: ScanScanIdResultRoute,
  ScanScanIdReviewRoute: ScanScanIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
